### ISSUE TITLE
Connect this screen to a raspberry Pi

### ISSUE THREAD

**Issue by jgoncalocouto** [juliandroid/DWIN_CR_10s_Pro#3]
Hey!

I'm way over my head here.
Basically I have this screen (DMT48270C043_06WT) in a Longer LK4 Pro.
I want to use it directly to a raspberry pi running Octopi.
Do you known how to connect it? Do I need an interface board? Can I buy that somewhere? I can't find that info anywhere.

**Comment by juliandroid** [comment]
This is just a display controller and I'm not aware for any direct way to connect it. Marlin 2.0 has support for this display, so you need a board that works with Marlin.

**Comment by jgoncalocouto** [comment]
Thanks for the clarification 🤙
